<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>

		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>

		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

  <ItemGroup>

  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="LLamaSharp" Version="0.25.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.1" />
	</ItemGroup>


</Project>
